### ISSUE TITLE
Anomalie versione Sympy

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/project_nolimit_math#3]
La versione Sympy presenta diverse anomalie e alcune cose da migliorare.
Le segnalo qui di seguito e confido in te @mone27 per la risoluzione.
1. Aprire SOLO UNA finestra "grafico dettagliato" -> ora ne apre infinite (inoltre assegnare al grafico il colore ROSSO e non BLU e, in caso, rimuovere quegli assi cartesiani con coordinate che rendono più confusionaria la lettura del grafico avendo i valori x e y al centro e sugli assi stessi, invece che al lato --> vedi versione Normale)
2. Dare la possibilità di inserire "inf" o "∞" come valore di x0 (controllare anche il segno -> +inf/+∞ o -inf/-∞ --> se "senza" segno bisogna assegnare in automatico il "+")
3. Se il risultato risulta infinito NON restituire "oo" ma "∞" (CON IL RELATIVO SEGNO! -> in caso calcolare se è ± o ∓)
4. Il risultato NON deve essere "frazionario" (ho notato che molte volte il risultato è frazionario, del tipo "3/7" 

(Ho notato che si può inf ad x0, ma non funziona bene --> vedi "lim per x->inf di f(x)= x/x**2 === restituisce "1/inf" -> dovrebbe restituire "0" -> anche il grafico NON è corretto (se invece di "inf" ci fosse "oo" funziona tutto ok)).

**Comment by Sav22999** [comment]
@mone27 TI RINGRAZIO PER TUTTO L'IMPEGNO DEDICATO NELLA VERSIONE SYMPY, HAI FATTO UN LAVORO ECCELLENTE ED E' QUASI PERFETTO :smile:

**Comment by mone27** [comment]
sul o 4 perchè non deve essere frazionario è molto meglio in quel modo

**Comment by Sav22999** [comment]
No. Io voglio il numero non la frazione! 😂😂

**Comment by Sav22999** [comment]
O, al massimo, se è frazionario fai comparire una textbox affianco che mostra la frazione, ma il numero lo voglio non frazionario per favore

**Comment by mone27** [comment]
Okay, preferisci i float alle frazioni? ma mi adeguo :)

**Comment by Sav22999** [comment]
Puoi mettere entrambi :wink:, però tra i due si

**Comment by mone27** [comment]
Penso che posso chiudere

**Comment by Sav22999** [comment]
Nope. Devi aggiustare il grafico!!!! Vedi quello sella versione normale

**Comment by mone27** [comment]
ho fatto come fai te per il grafico dettagliato con un piccolo miglioramento, quindi penso che vada bene
