### ISSUE TITLE
versione normale crasha con input incompleto

### ISSUE THREAD

**Issue by mone27** [Sav22999/project_nolimit_math#4]
mettendo nel numeratore una cosa tipo "6-" e mettendo in x0 un valore valido il programma crasha con questo errore:
`Traceback (most recent call last):
X(0): OK | Normal
  File "project_nolimit_math/nolimit/main.py", line 180, in onClickCalcola
Numerator: OK
    numeratore = calcolaNumDen(self.textNumeratore.text(), x0, False)
  File "/project_nolimit_math/nolimit/main.py", line 86, in calcolaNumDen
    c += int(array[0]);
ValueError: invalid literal for int() with base 10: '-'`

**Comment by Sav22999** [comment]
Ma perché non devi mettere 6- :joy: al massimo -6... L'equazione deve essere del tipo ax^2+bx+c

**Comment by Sav22999** [comment]
Non puoi scrivere tipo 6-x... usare la versione sympy :)

**Comment by mone27** [comment]
Ma se ho live updates attivato e sto cancellando l'espressione tac  crasha

**Comment by mone27** [comment]
Quindi due soluzioni o rimuovi live updates o implementi un controllo magari con una regex  dell'input. A limite limite metti un bel try except davanti a tutto(come faccio io), ma l'app può non funzionare ma non crashare!!!

**Comment by Sav22999** [comment]
Vedo di risolvere. Grazie della segnalazione :) (non mi era mai crashata!)

**Comment by Sav22999** [comment]
@mone27 a me l'applicazione non va in crash. Il try lo metto ugualmente, perché è giusto che vada, ma non capisco come faccia ad andare in errore...
Ad x0 cosa hai dato? e al denominatore? e al numeratore? specifica tutto per favore...

**Comment by Sav22999** [comment]
Risolto, aspetto una tua conferma @mone27 e chiudo :+1:  (o chiudilo tu direttamente :smile:)

**Comment by mone27** [comment]
@Sav22999 il bug è risolto solo parzialmente, se metto "6-" un valore su x0 e poi faccio calcola crasha come prima.

**Comment by Sav22999** [comment]
@mone27 Prova con la versione 1.0.4B non dovrebbe più presentare problemi.
